version: '3.8'

services:
  ib-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/log/docker/${COMPOSE_PROJECT_NAME}/app:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      ib-redis:
        condition: service_healthy

  ib-payment-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://ib-redis:6379
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /var/log/docker/${COMPOSE_PROJECT_NAME}/payment-worker:/app/logs
    restart: unless-stopped
    depends_on:
      ib-redis:
        condition: service_healthy

  ib-redis:
    image: redis:alpine
    volumes:
      - ib-redis-data:/data
    command: redis-server --appendonly yes  # Enable persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  ib-app-logs:
    driver: local
  ib-payment-worker-logs:
    driver: local
  ib-redis-data:
    driver: local