version: '3.8'

services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/log/docker/imaginebox:/app/logs
    networks:
      - coolify
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  coolify:
    external: true