export default function TermsPage() {
  return (
    <div className="flex flex-col gap-20 py-40 items-center px-60 ">
      <h1 className="text-4xl font-bold">Terms & Conditions</h1>
      <div>
      Welcome to [Your Web Client Name]! These Terms of Service (“Terms”) govern your access to and use of our web client for image generation models (the “Service”). By accessing or using the Service, you agree to these Terms. If you do not agree, please do not use the Service.

1. Use of Service
1.1 Eligibility
To use the Service, you must be at least 18 years old and have the legal capacity to enter into binding agreements.

1.2 User Accounts
You may need to create an account to access certain features of the Service. You are responsible for maintaining the confidentiality of your account and password. You are responsible for any activity that occurs through your account.

1.3 Use of APIs
The Service allows you to interface with image generation models (such as DALL-E, Stable Diffusion, etc.) using your own API keys. You agree to comply with the terms and conditions of the APIs you use and are responsible for maintaining your own API keys.

1.4 Prohibited Activities
You agree not to:

Use the Service for any unlawful purpose.
Violate the intellectual property rights of others.
Generate content that is harmful, abusive, harassing, or defamatory.
Attempt to gain unauthorized access to the Service or any systems or networks connected to it.
2. User Content and Generated Images
2.1 Generated Content
You retain ownership of any images or content generated using the Service. However, by using the Service, you grant us a worldwide, royalty-free, non-exclusive license to store and display the content for the purpose of operating and improving the Service.

2.2 Responsibility for Content
You are solely responsible for any content you generate or upload using the Service. We do not monitor or review content generated by users, but we reserve the right to remove any content that violates these Terms.

2.3 Prohibited Content
You may not use the Service to generate or distribute content that is illegal, obscene, hateful, or otherwise inappropriate. This includes content that promotes violence, discrimination, or violates the rights of others.

3. Fees and Payment
3.1 Service Fees
Access to certain features of the Service may require payment of fees. These fees will be clearly outlined at the time of purchase, and you agree to pay all applicable charges.

3.2 Refunds
All payments made through the Service are non-refundable, unless otherwise stated in writing.

4. Intellectual Property
4.1 Service Ownership
All rights, titles, and interests in the Service, including but not limited to the software, design, and features, are owned by [Your Company Name] or its licensors.

4.2 Trademarks
[Your Company Name], the [Your Web Client Name] logo, and other trademarks related to the Service are trademarks of [Your Company Name]. You may not use any trademarks without our prior written consent.

5. Limitation of Liability
To the fullest extent permitted by law, [Your Company Name] shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, revenue, data, or use, arising out of your use of the Service.

6. Indemnification
You agree to indemnify and hold [Your Company Name] harmless from any claims, damages, liabilities, costs, or expenses arising from your use of the Service, violation of these Terms, or infringement of any third-party rights.

7. Termination
We may suspend or terminate your access to the Service at any time without notice if we believe you have violated these Terms. Upon termination, your rights to use the Service will immediately cease.

8. Changes to the Terms
We reserve the right to modify these Terms at any time. If we make changes, we will notify you by updating the “Last Updated” date at the top of these Terms. Your continued use of the Service after changes are made constitutes your acceptance of the new Terms.

9. Governing Law
These Terms are governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of laws principles.

10. Contact Us
If you have any questions about these Terms, please contact us at [Your Contact Email].
      </div>
    </div>
  )
}