export const TERMS = [
    {
        name: "1. Use of Service",
        content: "",
        subterms: [
            {
                name: "1.1 Eligibility",
                content: "To use the Service, you must be at least 18 years old and have the legal capacity to enter into binding agreements."
            },
            {
                name: "1.2 User Accounts",
                content: "You may need to create an account to access certain features of the Service. You are responsible for maintaining the confidentiality of your account and password. You are responsible for any activity that occurs through your account."
            },
            {
                name: "1.3 Use of APIs",
                content: "The Service allows you to interface with image generation models (such as DALL-E, Stable Diffusion, etc.) using your own API keys. You agree to comply with the terms and conditions of the APIs you use and are responsible for maintaining your own API keys."
            },
            {
                name: "1.4 Prohibited Activities",
                content: "You agree not to: Use the Service for any unlawful purpose. Violate the intellectual property rights of others. Generate content that is harmful, abusive, harassing, or defamatory. Attempt to gain unauthorized access to the Service or any systems or networks connected to it."
            }
        ]
    },
    {
        name: "2. User Content and Generated Images",
        content: "",
        subterms: [
            {
                name: "2.1 Generated Content",
                content: "You retain ownership of any images or content generated using the Service. However, by using the Service, you grant me, [Your Full Name], a worldwide, royalty-free, non-exclusive license to store and display the content for the purpose of operating and improving the Service."
            },
            {
                name: "2.2 Responsibility for Content",
                content: "You are solely responsible for any content you generate or upload using the Service. I do not monitor or review content generated by users, but I reserve the right to remove any content that violates these Terms."
            },
            {
                name: "2.3 Prohibited Content",
                content: "You may not use the Service to generate or distribute content that is illegal, obscene, hateful, or otherwise inappropriate. This includes content that promotes violence, discrimination, or violates the rights of others."
            }
        ]
    },
    {
        name: "3. Fees and Payment",
        content: "",
        subterms: [
            {
                name: "3.1 Service Fees",
                content: "Access to certain features of the Service may require payment of fees. These fees will be clearly outlined at the time of purchase, and you agree to pay all applicable charges."
            },
            {
                name: "3.2 Refunds",
                content: "All payments made through the Service are non-refundable, unless otherwise stated in writing."
            }
        ]
    },
    {
        name: "4. Intellectual Property",
        content: "",
        subterms: [
            {
                name: "4.1 Service Ownership",
                content: "All rights, titles, and interests in the Service, including but not limited to the software, design, and features, are owned by me, [Your Full Name]."
            },
            {
                name: "4.2 Trademarks",
                content: "Any trademarks associated with [Your Web Client Name] or the Service are owned by me, [Your Full Name]. You may not use any trademarks without my prior written consent."
            }
        ]
    },
    {
        name: "5. Limitation of Liability",
        content: "To the fullest extent permitted by law, I, [Your Full Name], shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, revenue, data, or use, arising out of your use of the Service.",
        subterms: []
    },
    {
        name: "6. Indemnification",
        content: "You agree to indemnify and hold me, [Your Full Name], harmless from any claims, damages, liabilities, costs, or expenses arising from your use of the Service, violation of these Terms, or infringement of any third-party rights.",
        subterms: []
    },
    {
        name: "7. Termination",
        content: "I may suspend or terminate your access to the Service at any time without notice if I believe you have violated these Terms. Upon termination, your rights to use the Service will immediately cease.",
        subterms: []
    },
    {
        name: "8. Changes to the Terms",
        content: "I reserve the right to modify these Terms at any time. If I make changes, I will notify you by updating the \"Last Updated\" date at the top of these Terms. Your continued use of the Service after changes are made constitutes your acceptance of the new Terms.",
        subterms: []
    },
    {
        name: "9. Governing Law",
        content: "These Terms are governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of laws principles.",
        subterms: []
    },
    {
        name: "10. Contact Me",
        content: "If you have any questions about these Terms, please contact me at [Your Contact Email].",
        subterms: []
    }
]