import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "../components/nav/nav-bar"
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "sonner";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${jetbrainsMono.className} h-screen`}>
          <NavigationBar />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
